// Code generated by protoc-gen-go-grpc-vtpool. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc-vtpool v0.1.0
// source: store/storepb/rpc.proto

package storepb

import (
	context "context"
	sync "sync"

	vtproto "github.com/thanos-io/thanos/pkg/vtproto"
	grpc "google.golang.org/grpc"
)

func init() {
	for i, m := range WriteableStore_ServiceDesc.Methods {
		switch m.MethodName {
		case "RemoteWrite":
			WriteableStore_ServiceDesc.Methods[i].Handler = _WriteableStore_RemoteWrite_VTPoolHandler
		}
	}
}

func _WriteableStore_RemoteWrite_VTPoolHandler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := WriteRequestFromVTPool()
	wg := &sync.WaitGroup{}
	wg.Add(1)
	go func() {
		wg.Wait()
		in.ReturnToVTPool()
	}()
	defer wg.Done()
	ctx = vtproto.WithReturnWG(ctx, wg)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WriteableStoreServer).RemoteWrite(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WriteableStore_RemoteWrite_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WriteableStoreServer).RemoteWrite(ctx, req.(*WriteRequest))
	}
	return interceptor(ctx, in, info, handler)
}
