version: "2"
run:
  issues-exit-code: 1
output:
  formats:
    text:
      path: stdout
      print-linter-name: true
      print-issued-lines: true
linters:
  enable:
    - copyloopvar
    - goconst
    - godot
    - misspell
    - promlinter
    - unparam
  settings:
    errcheck:
      exclude-functions:
        - (github.com/go-kit/log.Logger).Log
        - fmt.Fprintln
        - fmt.Fprint
    goconst:
      min-occurrences: 5
    misspell:
      locale: US
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      # We don't check metrics naming in the tests.
      - linters:
          - promlinter
        path: _test\.go
      # These are not being checked since these methods exist
      # so that no one else could implement them.
      - linters:
          - unused
        text: SourceStoreAPI.implementsStoreAPI
      - linters:
          - unused
        text: SourceStoreAPI.producesBlocks
      - linters:
          - unused
        text: Source.producesBlocks
      - linters:
          - unused
        text: newMockAlertmanager
      - linters:
          - unused
        text: ruleAndAssert
      - linters:
          - unparam
        path: test/e2e/compatibility_test\.go
    paths:
      - vendor
      - internal/cortex
      - third_party$
      - builtin$
      - examples
formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - vendor
      - internal/cortex
      - third_party$
      - builtin$
      - examples
