// Copyright (c) The Thanos Authors.
// Licensed under the Apache License 2.0.

syntax = "proto3";
package thanos;

import "store/storepb/types.proto";
import "store/labelpb/types.proto";
import "google/protobuf/timestamp.proto";
import "tagger/tagger.proto";

option go_package = "github.com/thanos-io/thanos/pkg/rules/rulespb";

/// Rules represents API that is responsible for gathering rules and their statuses.
service Rules {
    /// Rules has info for all rules.
    /// Returned rules are expected to include external labels.
    rpc Rules(RulesRequest) returns (stream RulesResponse);
}

message RulesRequest {
    enum Type {
        ALL = 0;
        /// This will make sure strings.ToLower(.String()) will match 'alert' and 'record' values for
        /// Prometheus HTTP API.
        /// NOTE: The implementation has to return empty rule groups as well.
        ALERT  = 1;
        RECORD = 2;
    }
    Type type = 1;
    PartialResponseStrategy partial_response_strategy = 2;
    repeated string matcher_string = 3;
    repeated string rule_name = 4;
    repeated string rule_group = 5;
    repeated string file = 6;
}

message RulesResponse {
    oneof result {
        /// group for rule groups. It is up to server implementation to decide how many of those to put here within single frame.
        RuleGroup group = 1;

        /// warning is considered an information piece in place of series for warning purposes.
        /// It is used to warn rule API users about suspicious cases or partial response (if enabled).
        string warning = 2;
    }
}


/// RuleGroups is set of rule groups.
/// This and below APIs are meant to be used for unmarshaling and marshsaling rules from/to Prometheus API.
/// That's why json tag has to be customized and matching https://github.com/prometheus/prometheus/blob/c530b4b456cc5f9ec249f771dff187eb7715dc9b/web/api/v1/api.go#L955
/// NOTE: See rules_custom_test.go for compatibility tests.
///
/// For rule parsing from YAML configuration other struct is used: https://github.com/prometheus/prometheus/blob/20b1f596f6fb16107ef0c244d240b0ad6da36829/pkg/rulefmt/rulefmt.go#L105
message RuleGroups {
    repeated RuleGroup groups = 1 [(tagger.tags) = "json:\"groups\""];
}

/// RuleGroup has info for rules which are part of a group.
message RuleGroup {
    string name                               = 1 [(tagger.tags) = "json:\"name\""];
    string file                               = 2 [(tagger.tags) = "json:\"file\""];
    repeated Rule rules                       = 3 [(tagger.tags) = "json:\"rules\""];
    double interval                           = 4 [(tagger.tags) = "json:\"interval\""];
    double evaluation_duration_seconds        = 5 [(tagger.tags) = "json:\"evaluationTime\""]; // TODO: Is it really second?
    google.protobuf.Timestamp last_evaluation = 6 [(tagger.tags) = "json:\"lastEvaluation\""];
    int64 limit                               = 9 [(tagger.tags) = "json:\"limit\""];

    // Thanos specific.
    PartialResponseStrategy PartialResponseStrategy = 8 [(tagger.tags) = "json:\"partialResponseStrategy\""];
}

message Rule {
    oneof result {
        RecordingRule recording = 1;
        Alert alert= 2;
    }
}

/// AlertState represents state of the alert. Has to match 1:1 Prometheus AlertState:
//
// StateInactive is the state of an alert that is neither firing nor pending.
//StateInactive AlertState = iota
// StatePending is the state of an alert that has been active for less than
// the configured threshold duration.
//StatePending
// StateFiring is the state of an alert that has been active for longer than
// the configured threshold duration.
//StateFiring
enum AlertState {
    INACTIVE            = 0;
    PENDING             = 1;
    FIRING              = 2;
}

message AlertInstance {
    LabelSet labels                      = 1 [(tagger.tags) = "json:\"labels\""];
    LabelSet annotations                 = 2 [(tagger.tags) = "json:\"annotations\""];
    AlertState state                     = 3 [(tagger.tags) = "json:\"state\""];
    google.protobuf.Timestamp active_at  = 4 [(tagger.tags) = "json:\"activeAt,omitempty\""];
    string value                         = 5 [(tagger.tags) = "json:\"value\""];

    // Thanos specific. Used mainly for alert API purposes.
    PartialResponseStrategy PartialResponseStrategy = 6 [(tagger.tags) = "json:\"partialResponseStrategy\""];
}

message Alert {
    /// state returns the maximum state of alert instances for this rule.
    AlertState state                          = 1 [(tagger.tags) = "json:\"state\""];
    string name                               = 2 [(tagger.tags) = "json:\"name\""];
    string query                              = 3 [(tagger.tags) = "json:\"query\""];
    double duration_seconds                   = 4 [(tagger.tags) = "json:\"duration\""];
    LabelSet labels                           = 5 [(tagger.tags) = "json:\"labels\""];
    LabelSet annotations                      = 6 [(tagger.tags) = "json:\"annotations\""];
    repeated AlertInstance alerts              = 7 [(tagger.tags) = "json:\"alerts\""];
    string health                             = 8 [(tagger.tags) = "json:\"health\""];
    string last_error                         = 9 [(tagger.tags) = "json:\"lastError,omitempty\""];
    double evaluation_duration_seconds        = 10 [(tagger.tags) = "json:\"evaluationTime\""];
    google.protobuf.Timestamp last_evaluation = 11 [(tagger.tags) = "json:\"lastEvaluation\""];
    double keep_firing_for_seconds            = 12 [(tagger.tags) = "json:\"keepFiringFor\""];
}

message RecordingRule {
    string name                               = 1 [(tagger.tags) = "json:\"name\""];
    string query                              = 2 [(tagger.tags) = "json:\"query\""];
    LabelSet labels                           = 3 [(tagger.tags) = "json:\"labels\""];
    string health                             = 4 [(tagger.tags) = "json:\"health\""];
    string last_error                         = 5 [(tagger.tags) = "json:\"lastError,omitempty\""];
    double evaluation_duration_seconds        = 6 [(tagger.tags) = "json:\"evaluationTime\""];
    google.protobuf.Timestamp last_evaluation = 7 [(tagger.tags) = "json:\"lastEvaluation\""];
}
