// Copyright (c) The Thanos Authors.
// Licensed under the Apache License 2.0.

syntax = "proto3";

package queryfrontend;

import "store/labelpb/types.proto";
import "tagger/tagger.proto";

option go_package = "github.com/thanos-io/thanos/pkg/queryfrontend";

message ThanosLabelsResponse {
  string Status = 1 [(tagger.tags) = "json:\"status\""];
  repeated string Data = 2 [(tagger.tags) = "json:\"data\""];
  string ErrorType = 3 [(tagger.tags) = "json:\"errorType,omitempty\""];
  string Error = 4 [(tagger.tags) = "json:\"error,omitempty\""];
  repeated ResponseHeader Headers = 5 [(tagger.tags) = "json:\"-\""];
}

message ThanosSeriesResponse {
  string Status = 1 [(tagger.tags) = "json:\"status\""];
  repeated thanos.LabelSet Data = 2 [(tagger.tags) = "json:\"data\""];
  string ErrorType = 3 [(tagger.tags) = "json:\"errorType,omitempty\""];
  string Error = 4 [(tagger.tags) = "json:\"error,omitempty\""];
  repeated ResponseHeader Headers = 5 [(tagger.tags) = "json:\"-\""];
}

message ResponseHeader {
  string Name = 1 [(tagger.tags) = "json:\"-\""];
  repeated string Values = 2 [(tagger.tags) = "json:\"-\""];
}
